In [3]:
import pandas as pd 
import numpy as np

In [4]:
from multiprocessing import Pool
from multiprocessing import get_context

In [6]:
from itertools import chain

In [8]:
import xgboost as xgb

In [35]:
##Test Pull
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams 
all_teams = pd.DataFrame(teams.get_teams())
display(all_teams)
test_list = all_teams['abbreviation'].tolist()
print(test_list)

,abbreviation,city,full_name,id,nickname,state,year_founded
0,ATL,Atlanta,Atlanta Hawks,1610612737,Hawks,Atlanta,1949
1,BOS,Boston,Boston Celtics,1610612738,Celtics,Massachusetts,1946
2,CLE,Cleveland,Cleveland Cavaliers,1610612739,Cavaliers,Ohio,1970
3,NOP,New Orleans,New Orleans Pelicans,1610612740,Pelicans,Louisiana,2002
4,CHI,Chicago,Chicago Bulls,1610612741,Bulls,Illinois,1966
5,DAL,Dallas,Dallas Mavericks,1610612742,Mavericks,Texas,1980
6,DEN,Denver,Denver Nuggets,1610612743,Nuggets,Colorado,1976
7,GSW,Golden State,Golden State Warriors,1610612744,Warriors,California,1946
8,HOU,Houston,Houston Rockets,1610612745,Rockets,Texas,1967
9,LAC,Los Angeles,Los Angeles Clippers,1610612746,Clippers,California,1970
10,LAL,Los Angeles,Los Angeles Lakers,1610612747,Lakers,California,1948
11,MIA,Miami,Miami Heat,1610612748,Heat,Florida,1988
12,MIL,Milwaukee,Milwaukee Bucks,1610612749,Bucks,Wisconsin,1968
13,MIN,Minnesota,Minnesota Timberwolves,1610612750,Timberwolves,Minnesota,1989
14,BKN,Brooklyn,Brooklyn Nets,1610612751,Nets,New York,1976
15,NYK,New York,New York Knicks,1610612752,Knicks,New York,1946
16,ORL,Orlando,Orlando Magic,1610612753,Magic,Florida,1989
17,IND,Indiana,Indiana Pacers,1610612754,Pacers,Indiana,1976
18,PHI,Philadelphia,Philadelphia 76ers,1610612755,76ers,Pennsylvania,1949
19,PHX,Phoenix,Phoenix Suns,1610612756,Suns,Arizona,1968
20,POR,Portland,Portland Trail Blazers,1610612757,Trail Blazers,Oregon,1970
21,SAC,Sacramento,Sacramento Kings,1610612758,Kings,California,1948
22,SAS,San Antonio,San Antonio Spurs,1610612759,Spurs,Texas,1976
23,OKC,Oklahoma City,Oklahoma City Thunder,1610612760,Thunder,Oklahoma,1967
24,TOR,Toronto,Toronto Raptors,1610612761,Raptors,Ontario,1995
25,UTA,Utah,Utah Jazz,1610612762,Jazz,Utah,1974
26,MEM,Memphis,Memphis Grizzlies,1610612763,Grizzlies,Tennessee,1995
27,WAS,Washington,Washington Wizards,1610612764,Wizards,District of Columbia,1961
28,DET,Detroit,Detroit Pistons,1610612765,Pistons,Michigan,1948
29,CHA,Charlotte,Charlotte Hornets,1610612766,Hornets,North Carolina,1988

['ATL', 'BOS', 'CLE', 'NOP', 'CHI', 'DAL', 'DEN', 'GSW', 'HOU', 'LAC', 'LAL', 'MIA', 'MIL', 'MIN', 'BKN', 'NYK', 'ORL', 'IND', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'OKC', 'TOR', 'UTA', 'MEM', 'WAS', 'DET', 'CHA']

In [37]:
relevant_id = all_teams[all_teams['abbreviation'] == abbreviation]['id'].tolist()

NameError: name 'abbreviation' is not defined

In [31]:
##Function to pull teams and push into dataframe 

def team_df (abv) : 
    from nba_api.stats.endpoints import leaguegamefinder
    from nba_api.stats.static import teams 
    
    all_teams = pd.DataFrame(teams.get_teams())
    relevant_id = all_teams[all_teams['abbreviation'] == abbreviation]['id'].tolist()